23 컬럼 관리 기능
backendINFJ/b4-trello pull request #48
Opened 2024-07-12 08:23 UTC by Been777

## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>

2024-07-12 09:48 UTC, ckehqja requested changes
잘봤씁니다

2024-07-12 09:48 UTC, ckehqja commented on src/main/java/com/nbcamp/b4trello/controller/ColumnController.java
>  public class ColumnController {
'/api' 안붙이기로 했습니다 ㅎㅎ;;

2024-07-12 09:48 UTC, ckehqja commented on src/main/java/com/nbcamp/b4trello/controller/ColumnController.java
> +    }
반환타입이 ResponseEntity<CommonResponse<ColumnResponseDto>> 
CommonResponse에 넣어서 반환하기로 했어요 ㅎㅎ

2024-07-12 09:48 UTC, ckehqja commented on src/main/java/com/nbcamp/b4trello/dto/ColumnRequestDto.java
> +public class ColumnRequestDto {
저희 롬북을 사용하기로 했으니깐 '@Getter', '@Setter' 사용하면 더 깔끔하지 않을까요?

2024-07-12 09:48 UTC, ckehqja commented on src/main/java/com/nbcamp/b4trello/service/ColumnService.java
> +    private BoardRepository boardRepository;
생성자 주입은 추천하지 안는 방법입니다 
필더 주입 방식을 권장합니다

2024-07-12 10:47 UTC, backendINFJ commented
컬럼도 순서이동,프론트 구현 등 생각하면 쉽지 않았을 거 같은데 마감기한도 잘 지켜주셨네요! 너무 고생하셨습니다:)

2024-07-13 07:47 UTC, ckehqja reviewed
고생하셨습니다.

2024-07-13 07:50 UTC, ckehqja approved these changes

2024-07-13 07:54 UTC, merged